#!/bin/bash
echo "Setting up credentials for the interval service"
(

  PROJECT_MESHBLU_JSON="$PROJECT_DIR/nanocyte-interval-redis/meshblu.json"
  if [ ! -f "$PROJECT_MESHBLU_JSON" ]; then

    cd "$PROJECT_DIR/meshblu"
    echo "Starting meshblu"

    node server.js --http > /dev/null &
    meshblu_pid=$!
    sleep 10

    echo "registering nanocyte-interval-service"
    meshblu-util register -s localhost:3000 -t interval-service > $PROJECT_DIR/nanocyte-interval-redis/meshblu.json

    echo "registered. Copying to the interval-service"
    cp $PROJECT_DIR/nanocyte-interval-redis/meshblu.json $PROJECT_DIR/nanocyte-interval-service/meshblu.json

    meshblu-util update -p -f $INSTALL_DIR/config/interval-service-webhook.json $PROJECT_DIR/nanocyte-interval-redis/meshblu.json
    export NANOCYTE_INTERVAL_UUID=`cat $PROJECT_DIR/nanocyte-interval-redis/meshblu.json | jq --raw-output '.uuid'`

    kill $meshblu_pid
  fi
)
