#!/bin/bash
echo "Setting up credentials for nanocyte related services"
(
  INTERVAL_SERVICE_MESHBLU_CONFIG="$PROJECT_DIR/nanocyte-interval-redis/meshblu.json"
  CREDENTIALS_MESHBLU_CONFIG="$PROJECT_DIR/credentials-worker/meshblu.json"
  CREDENTIALS_PUBLIC_KEY="$PROJECT_DIR/credentials-service/public-key.json"
  NANOCYTE_PUBLIC_KEY="$PROJECT_DIR/nanocyte-engine-http/public-key.json"

  cd "$PROJECT_DIR/meshblu"
  echo "Starting meshblu"

  node server.js --http > /dev/null &
  meshblu_pid=$!
  sleep 10


  if [ ! -s "$INTERVAL_SERVICE_MESHBLU_CONFIG" ]; then
    echo "registering nanocyte-interval-service"
    meshblu-util register -s localhost:3000 -t interval-service > $PROJECT_DIR/nanocyte-interval-redis/meshblu.json

    echo "registered. Copying to the interval-service"
    cp $PROJECT_DIR/nanocyte-interval-redis/meshblu.json $PROJECT_DIR/nanocyte-interval-service/meshblu.json

    meshblu-util update -p -f $INSTALL_DIR/config/interval-service-webhook.json $PROJECT_DIR/nanocyte-interval-redis/meshblu.json
    export NANOCYTE_INTERVAL_UUID=`cat $PROJECT_DIR/nanocyte-interval-redis/meshblu.json | jq --raw-output '.uuid'`
  fi

  if [ ! -s "$CREDENTIALS_MESHBLU_CONFIG" ]; then
    echo "registering credentials-service"
    meshblu-util register -s localhost:3000 -t credentials-service > $PROJECT_DIR/credentials-worker/meshblu.json
    meshblu-util update -p -f $INSTALL_DIR/config/credentials-service-webhook.json $PROJECT_DIR/credentials-worker/meshblu.json

    export CREDENTIALS_SERVICE_UUID=`cat $PROJECT_DIR/credentials-worker/meshblu.json | jq --raw-output '.uuid'`
  fi

  if [ ! -s "$CREDENTIALS_PUBLIC_KEY" ]; then
    echo "getting the public key for credentials-service"
    curl --silent http://localhost:3000/publickey > $PROJECT_DIR/credentials-service/public-key.json
  fi

  if [ ! -s "$NANOCYTE_PUBLIC_KEY" ]; then
    echo "getting the public key for nanocyte-engine-http"
    curl --silent http://localhost:3000/publickey > $PROJECT_DIR/nanocyte-engine-http/public-key.json
  fi

  kill $meshblu_pid
)
